[package]
name = "get_inputs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
reqwest = "0.11.10"
futures = "0.3.21"
error-chain = "0.12.4"
tokio = "1.19.2"
